apiVersion: v1
kind: ConfigMap
metadata:
  name: forward-plugin-configmap
data:
  config.yaml: |
    dsn: "root:root@tcp(127.0.0.1:3306)/order_db?charset=utf8mb4&parseTime=True&loc=Local"
      
      
